version: '3'
services:
  frontend:
    build: ./frontend
    image: adams_front:1
    container_name: front
    command: yarn dev
    volumes:
      - ./frontend:/workspace:cached
      - /workspace/node_modules
    networks:
      - front-tier
      - back-tier
    ports:
      - 3000:3000
    tty: true
    depends_on:
      - db

  backend:
    build: ./backend
    image: adams_back:1
    container_name: back
    command: air
    volumes:
      - ./backend:/workspace:cached
    networks:
      - front-tier
      - back-tier
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db

  db:
    image: postgres:alpine
    container_name: adams_db
    volumes:
      - adams_db_volume:/var/lib/postgresql/data
    networks:
      - back-tier
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=adams
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:5.0
    container_name: pgadmin4
    volumes:
      - adams_pgadmin_volume:/var/lib/pgadmin
    networks:
      - back-tier
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8000:80
    depends_on:
      - db

networks:
  front-tier:
  back-tier:

volumes:
  adams_db_volume:
    external: true
  adams_pgadmin_volume:
    external: true
