name: Github Pages
on:
  push:
    branches:
      - master
    paths:
      - 'doc/**/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install NPM packages
        run: yarn install
        working-directory: ./docs
      - name: Build website
        run: npm run build
        working-directory: ./docs
      - name: Deploy website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/dist
